env:
  global:
  - secure: mjnV1b4/1s+o8w6pgk27V8W9id8bZuGZjTEh/Athv4o29Fi1gL1POepLltYM3Tetx6MbHS0lWMp9KcKxPUIZ8gSUvd9VVP0341nktSMqGVRANtWNOnhsZ/APG50dxbIPl76HkxbgJRR4JAHRYoS1hNn+kgNwk6ouGy7V9qHHTU6/S3tX6Y1dKbIVwUCovuPfF5VztRaJVWRQrTZsAueP04WoJEdxZKcNHrT3DYe9ANUAogNFfbBQCiPWxkySRcyCFNPRr+3xjlB0FecbIjt6HQe9/Abog42nQqrJSeVLWKVgVcqBLz2q4AGM+M80ir8eE0G0JCCZmhRGHJaibOFMI29DnU8+7GYHt9UxKv9k7+wSZppaS/y+klLteFjbSXNeqfn10VeInEpFcOenF7rKex/0icB1xbigrECxmkKkVT9Ib0XKojMvHZLtSrURDfRWfJjw1O4fntUaPI1VlmgBd4Ox06fGdw72RvPHL0EITWJHqd7+elULHLi8e8dcNs4f/XkFVvqqG66Mzu9cBga0niWiA7QhO2mnrn+EUckziW8P2PM3lCT3sKi/mrno6UAq+lehMJHZXsd9fPJrjUJ4eFs63ZSp+MGOhguEX+zrgpJtwoRTitUnf12FNfmbPksLsxMed6AyALOfd9MflhmbZOjzPQ2NryRsUwQ/LbuwyWw=
  - secure: rSVEwXFEvvsUMx8F2fB6ESmgGbqrgKrgxDus2YrmbJU5zUELCyVem9EqApgrd/XcP+Ql+U42cZIuJzQEOdHMX3AWnRMKUql/L3ebSn9vGvJ5X5YWTtq+iVCQeqfvkufn/RCm8oTuCx7ESU8eXJ28Ke9Ek1m9GY8d9Q/Ef9zzadZz4SmGMdLTbLO/v8VQjNYU84MdLH2+Qc1EVgl9TiqclzA+WawLkFDh8WCQzRMmrr+7O9R57twxiXulRs8xs5+3QQ6uJ6WptwyAElxs4bYFUgKJjy3Rf8oWxbLCqg5NOVtOdVoBaIiXpaqE05LvAiKeG8r5UJhBO2bX6ffm80jFRcUnlZwYkRy3lyfNCQpAEdAIlUVzpjWUmlQPfoDNBlKL0/pB//h7n+YxZWxdyQcCzXI9OdISLuZlhmSwtAwHjw6VV4GPB2TISkmwAfaCfzcGc0GTC3tZNgI5G7snUPuxLGh/jgwpY3HHItfZHct+C91lq647duoYJ1sr6Tjwq45vZG+RpZpNc0H5dpnG+eVjhVAmWzPmyWEbv7J0+a4e0FBcSSdYsdDeEZAEaf9/KFIdH0AsiL+mSjzF7+iUVp1xopwywpt9Bn1mYnaxAV07GvQxtgAElnQBMDn2qhebJSh66Dz8GvjQWbHCYOqO6+0y1HEVG46JtqbgHPJVrSEBGdY=
language: node_js
install:
 - npm install
 script:
- npm start
 
after_success:
 gulp deploy --user $FTP_USER --password $FTP_PASSWORD 


